# Application root-application

application_metadata_name:  "root-application"
application_metadata_namespace: "default"
application_destination_namespace: "default"
application_destination_name: "in-cluster"
application_project: "root-application"
application_source_repo_url: "https://github.com/tbazz/gitops-app-of-apps.git"
application_source_path: "root-applications"

# Project root-application

project_metadata_name:  "root-application"
project_metadata_namespace: "default"
project_destination_namespace: "*"
project_destination_name: "in-cluster"
project_destination_server: "https://kubernetes.default.svc"
project_source_repo_url: "https://github.com/tbazz/gitops-app-of-apps.git"

# Repository root-application

repository_metadata_name:  "https://github.com/tbazz/gitops-app-of-apps.git"
repository_metadata_namespace: "default"
repository_stringData_url: "https://github.com/tbazz/gitops-app-of-apps.git"
